
-- bi_events unified event log for all domains (bookings, payments, search, user)
-- Design: "envelope + payload"  a stable, typed envelope every event shares,
-- plus a flexible JSON payload for event-type-specific attributes.
-- New event types and new domains = new ROWS (new values), never new columns.
-- Dialect: BigQuery (Standard SQL / GoogleSQL)

CREATE TABLE IF NOT EXISTS analytics.bi_events (

  -- classification & linking 
  event_id          STRING    NOT NULL OPTIONS (description = 'Unique event ID generated by the PRODUCING service (not at load time) — the idempotency key: a retried/replayed event carries the same ID, making dedup trivial'),
  event_domain      STRING    NOT NULL OPTIONS (description = 'Business domain of the event process: booking | payment | search | user. Coarse and stable; adding a domain is a data change, not a schema change'),
  event_name        STRING    NOT NULL OPTIONS (description = 'What happened, in object_action convention (booking_approved, payment_charged, search_performed). Fine-grained taxonomy lives in the naming convention + event registry, not in extra columns'),
  entity_type       STRING    NOT NULL OPTIONS (description = 'Type of the thing the event happened TO (booking, payment, hotel, user) — resolves which table entity_id joins to. Kept separate from event_domain for cross-domain events (e.g. a search-domain click on a hotel entity)'),
  entity_id         STRING    NOT NULL OPTIONS (description = 'ID of the entity the event happened to — the join key (bkg_555, pay_610)'),
  subject_user_id   STRING             OPTIONS (description = 'Whose journey this event belongs to (usually the traveler) — distinct from the actor: an approver acts, but the event is still part of the traveler''s story'),
  correlation_id    STRING             OPTIONS (description = 'Shared ID threading one end-to-end flow (search → book → approve → pay) across services — makes cross-service journey reconstruction a GROUP BY, not a multi-way join'),
  actor_type        STRING             OPTIONS (description = 'Who/what caused the event: traveler | approver | admin | system'),
  actor_id          STRING             OPTIONS (description = 'Specific user or system that performed the action (usr_31, stripe_webhook, scheduler)'),

  -- lifecycle & ordering
  previous_status   STRING             OPTIONS (description = 'For lifecycle events: status before the transition (e.g. requested). NULL for non-lifecycle events (searches, clicks). Promoted to a typed envelope column because status transitions are the analytical backbone for BOTH bookings and payments'),
  new_status        STRING             OPTIONS (description = 'For lifecycle events: status after the transition (e.g. approved). NULL for non-lifecycle events'),
  occurred_at       TIMESTAMP NOT NULL OPTIONS (description = 'When the event happened in the real world, set by the source service (millisecond precision)'),
  received_at       TIMESTAMP          OPTIONS (description = 'When the pipeline first received the event — the gap vs occurred_at surfaces late arrivals and service lag'),
  loaded_at         TIMESTAMP          OPTIONS (description = 'When the row landed in this table — for debugging ingestion/batch issues; BigQuery time travel (FOR SYSTEM_TIME AS OF, 7 days) covers table-state investigation beyond this'),
  sequence_number   INT64              OPTIONS (description = 'Monotonic counter per source service — deterministic ordering tiebreaker when multiple transitions share the same timestamp (transitions can fire milliseconds apart)'),

  -- provenance & payload 
  source_service    STRING             OPTIONS (description = 'Backend service that emitted the event (booking-svc, payment-svc, approval-svc)'),
  environment       STRING             OPTIONS (description = 'prod | staging | synthetic — keeps test and automated/bot traffic (which Arbitrip explicitly receives) out of business metrics without deleting it'),
  schema_version    INT64              OPTIONS (description = 'Version of this event type''s payload contract — payloads evolve per event type without any change to this table'),
  payload           JSON               OPTIONS (description = 'All event-type-specific attributes (amounts, destinations, policies, provider references). The flexible half of the design: new event types add JSON fields here, never columns. Hot fields get promoted to typed columns in dbt staging models downstream')

)
-- physical layout: at "hundreds of millions of rows" (per Arbitrip's landscape),an unpartitioned event log is a cost bomb under BigQuery scan-based pricing.
PARTITION BY DATE(occurred_at)          -- time is the universal access pattern for an event log
CLUSTER BY event_domain, event_name     -- all payment events last week" scans a sliver, not the table
OPTIONS (
  description = 'Unified append-only event log across all product domains. Envelope+payload design: structural stability with payload flexibility. Append-only: events are immutable facts; state is DERIVED downstream, never updated in place.',
  require_partition_filter = TRUE        -- forces every query to bound its scan — cost guardrail
);
